<a href="https://colab.research.google.com/github/lostysky/Data-Engineering-codeboosters-internship-2026/blob/main/Day_01__Introduction_to_Data_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

print("libraries imported successfully!")

libraries imported successfully!

In [ ]:
df=pd.read_csv("/content/student_performance.csv")
print ("dataset loaded successfully!")

dataset loaded successfully!

In [ ]:
df

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("number of row and columns :",df.shape)

number of row and columns : (30, 13)

In [ ]:
print("number of student(row)",df.shape[0])

number of student(row) 30

In [ ]:
print("number of coloumns",df.shape[1])

number of coloumns 13

In [ ]:
print("coloumn in the dataset")
print(df.columns.tolist())

coloumn in the dataset
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [ ]:
print("datatypes")
print(df.dtypes)

datatypes
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
print("missing values in the column:")
print(df.isnull().sum())

missing values in the column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print("student name:")
print (df['name'])

student name:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print("department in this dataset:")
print(df['department'].unique())

department in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print("how many student per department ")
print(df['department'].value_counts())

how many student per department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
cs_student=df[df['department']=='Computer Science']

In [ ]:
print(f"number of computer science student:{len(cs_student)}")

number of computer science student:13

In [ ]:
print("computer science student:")
print(cs_student[['name','math_score','programming_score','attendance_percentage']])

computer science student:
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [ ]:
high_attendance=df[df['attendance_percentage']>90]

In [ ]:
print(f"students with attendance above 90%:{len(high_attendance)}")

students with attendance above 90%:10

In [ ]:
print(high_attendance[['name','math_score','programming_score','attendance_percentage']])

              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
3      Sneha Reddy          70                 48                     95
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
13   Kavya Nambiar          74                 51                     91
15    Ritu Agarwal          87                 69                     93
17  Swati Kulkarni          90                 92                     94
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
29  Akanksha Yadav          91                 94                     95

In [ ]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
df['total_score'].head()

0    326
1    325
2    255
3    273
4    356
Name: total_score, dtype: int64

In [ ]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)

In [ ]:
df_sorted=df.sort_values(by='total_score',ascending=False).head(10)
print("Top 10 studens by total score")
df_sorted

Top 10 studens by total score

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023,371
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023,367
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023,365
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023,356
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023,354
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023,336
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023,334
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023,327
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326

In [ ]:
print('----------------------------------------------------------')
print('                Student Data Explorer')
print('----------------------------------------------------------')
print('Total Number of Students:',end=" ")
print(len(df))
print("Total Number of Columns:",end=" ")
print(df.shape[1])
print("Number of unique departments:",end=" ")
print(df['department'].nunique())
print("Number of Students per department:",end=" ")
print(df['department'].value_counts())
high_math=df['math_score'].max()
print(f'Highest math score:{high_math}')
low_math=df['math_score'].min()
print(f'Lowest math score:{low_math}')
avg_math=df['math_score'].mean()
print(f'Average math score:{avg_math}')
avg_prog=df['programming_score'].mean()
print(f'Avergae Programming Score:{avg_prog}')
avg_att=df['attendance_percentage'].mean()
print(f'Average Attendance Percentage:{avg_att}')
gender_avg=df.groupby('gender')['total_score'].mean().round(2)
print(f"Average Total Score grouped by gender:{gender_avg}")
df_sorted=df.sort_values(by='total_score',ascending=False)
print("Top 5 students by total score")
print(df_sorted[['name','department','total_score']].head(5))
low_att=df[df['attendance_percentage']<75]
print("Students with low attendance percentage:")
print(low_att[['name','department','attendance_percentage']])

----------------------------------------------------------
                Student Data Explorer
----------------------------------------------------------
Total Number of Students: 30
Total Number of Columns: 14
Number of unique departments: 4
Number of Students per department: department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64
Highest math score:95
Lowest math score:56
Average math score:76.06666666666666
Avergae Programming Score:67.6
Average Attendance Percentage:84.5
Average Total Score grouped by gender:gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64
Top 5 students by total score
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356
Students with low attendance percentage:
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73